import { UserProfile, AttendanceRecord } from '../types';
import { getISTTime } from './timeUtils';

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'admin_1',
    name: 'Dr. V. Rajesh (Chief Warden)',
    email: 'admin@hostelmess.edu',
    role: 'admin',
    createdAt: '2026-01-01',
  },
  {
    id: 'manager_1',
    name: 'Ramesh Sharma (Mess Manager)',
    email: 'manager@hostelmess.edu',
    role: 'mess_manager',
    createdAt: '2026-01-01',
  },
  {
    id: 'stu_saravanavel',
    name: 'Saravanavel J',
    email: 'saravanavelj5@gmail.com',
    role: 'student',
    studentId: 'ES24AM46',
    roomNumber: '007',
    department: 'AI&ML',
    createdAt: '2026-01-05',
  },
  {
    id: 'stu_101',
    name: 'Arun',
    email: 'arun@hostelmess.edu',
    role: 'student',
    studentId: 'STU101',
    roomNumber: 'B-204',
    department: 'Computer Science',
    createdAt: '2026-01-10',
  },
  {
    id: 'stu_102',
    name: 'Kumar',
    email: 'kumar@hostelmess.edu',
    role: 'student',
    studentId: 'STU102',
    roomNumber: 'B-205',
    department: 'Electronics & Comm',
    createdAt: '2026-01-10',
  },
  {
    id: 'stu_103',
    name: 'Ravi',
    email: 'ravi@hostelmess.edu',
    role: 'student',
    studentId: 'STU103',
    roomNumber: 'A-108',
    department: 'Mechanical Eng',
    createdAt: '2026-01-11',
  },
  {
    id: 'stu_104',
    name: 'Priya',
    email: 'priya@hostelmess.edu',
    role: 'student',
    studentId: 'STU104',
    roomNumber: 'C-312',
    department: 'Information Tech',
    createdAt: '2026-01-12',
  },
  {
    id: 'stu_105',
    name: 'Sneha',
    email: 'sneha@hostelmess.edu',
    role: 'student',
    studentId: 'STU105',
    roomNumber: 'C-315',
    department: 'Civil Engineering',
    createdAt: '2026-01-12',
  },
  {
    id: 'stu_106',
    name: 'Karthik',
    email: 'karthik@hostelmess.edu',
    role: 'student',
    studentId: 'STU106',
    roomNumber: 'A-110',
    department: 'Electrical Eng',
    createdAt: '2026-01-15',
  },
  {
    id: 'stu_107',
    name: 'Divya',
    email: 'divya@hostelmess.edu',
    role: 'student',
    studentId: 'STU107',
    roomNumber: 'C-302',
    department: 'Biotechnology',
    createdAt: '2026-01-15',
  },
  {
    id: 'stu_108',
    name: 'Manoj',
    email: 'manoj@hostelmess.edu',
    role: 'student',
    studentId: 'STU108',
    roomNumber: 'B-210',
    department: 'Chemical Eng',
    createdAt: '2026-01-16',
  },
];

export function getInitialAttendance(dateStr?: string): AttendanceRecord[] {
  const date = dateStr || getISTTime().dateString;

  return [
    {
      id: `STU101_${date}`,
      studentId: 'STU101',
      studentName: 'Arun',
      roomNumber: 'B-204',
      department: 'Computer Science',
      date,
      breakfast: 'available',
      lunch: 'not_available',
      dinner: 'available',
      updatedAt: new Date().toISOString(),
    },
    {
      id: `STU102_${date}`,
      studentId: 'STU102',
      studentName: 'Kumar',
      roomNumber: 'B-205',
      department: 'Electronics & Comm',
      date,
      breakfast: 'available',
      lunch: 'available',
      dinner: 'not_available',
      updatedAt: new Date().toISOString(),
    },
    {
      id: `STU103_${date}`,
      studentId: 'STU103',
      studentName: 'Ravi',
      roomNumber: 'A-108',
      department: 'Mechanical Eng',
      date,
      breakfast: 'not_available',
      lunch: 'available',
      dinner: 'available',
      updatedAt: new Date().toISOString(),
    },
    {
      id: `STU104_${date}`,
      studentId: 'STU104',
      studentName: 'Priya',
      roomNumber: 'C-312',
      department: 'Information Tech',
      date,
      breakfast: 'available',
      lunch: 'available',
      dinner: 'available',
      updatedAt: new Date().toISOString(),
    },
    {
      id: `STU105_${date}`,
      studentId: 'STU105',
      studentName: 'Sneha',
      roomNumber: 'C-315',
      department: 'Civil Engineering',
      date,
      breakfast: 'available',
      lunch: 'not_available',
      dinner: 'available',
      updatedAt: new Date().toISOString(),
    },
    {
      id: `STU106_${date}`,
      studentId: 'STU106',
      studentName: 'Karthik',
      roomNumber: 'A-110',
      department: 'Electrical Eng',
      date,
      breakfast: 'not_available',
      lunch: 'not_available',
      dinner: 'available',
      updatedAt: new Date().toISOString(),
    },
    {
      id: `STU107_${date}`,
      studentId: 'STU107',
      studentName: 'Divya',
      roomNumber: 'C-302',
      department: 'Biotechnology',
      date,
      breakfast: 'available',
      lunch: 'available',
      dinner: 'not_submitted',
      updatedAt: new Date().toISOString(),
    },
    {
      id: `STU108_${date}`,
      studentId: 'STU108',
      studentName: 'Manoj',
      roomNumber: 'B-210',
      department: 'Chemical Eng',
      date,
      breakfast: 'not_submitted',
      lunch: 'available',
      dinner: 'available',
      updatedAt: new Date().toISOString(),
    },
  ];
}
